version: "3.3"
services:
  ipfs:
    image: surfdb/ceramic-js-daemon:latest
    ports:
      - "5001:5001"
      - "8011:8011"
      - "8080:8080"
    volumes:
      - ./ipfs:/data/ipfs
    environment:
      - IPFS_ENABLE_S3=true
      - IPFS_S3_REGION=${IPFS_S3_REGION}
      - IPFS_S3_BUCKET_NAME=${IPFS_S3_BUCKET_NAME}
      - IPFS_S3_ROOT_DIRECTORY=surf
      - IPFS_S3_ACCESS_KEY_ID=${IPFS_S3_ACCESS_KEY_ID}
      - IPFS_S3_SECRET_ACCESS_KEY=${IPFS_S3_SECRET_ACCESS_KEY}
      - IPFS_S3_REGION_ENDPOINT=${IPFS_S3_REGION_ENDPOINT}
      - IPFS_S3_Key_TRANSFORM=next-to-last/2

  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    ports:
      - "7007:7007"
    volumes:
      - ./ceramic:/root/.ceramic
    depends_on:
      - ipfs
    environment:
      - NODE_ENV=production

volumes:
  ipfs:
  ceramic:
