version: "3.3"
services:
  ipfs:
    image: ceramicnetwork/go-ipfs-daemon:latest
    ports:
      - "5001:5001"
      - "8011:8011"
    volumes:
      - ./ipfs:/data/ipfs

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  ceramic:
    image: ceramicnetwork/js-ceramic:latest
    ports:
      - "7007:7007"
    volumes:
      - ./ceramic:/root/.ceramic
    depends_on:
      - ipfs
      - db
    environment:
      - NODE_ENV=production
      - CERAMIC_ENABLE_EXPERIMENTAL_COMPOSE_DB=true

volumes:
  ipfs:
  ceramic:
  db:
